// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedaquestionmarktodatetime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedaquestionmarktodatetime));
        
        string IMigrationMetadata.Id
        {
            get { return "201810311344155_added a question mark to datetime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
